---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-transfer-deployment
spec:
  selector:
    matchLabels:
      app: msg-transfer 
  replicas: 12 
  template:
    metadata:
      labels:
        app: msg-transfer
    spec:
      containers:
      - name: msg-transfer
        image: openim/msg_transfer:errcode_alpha
        command: ["./main"]
        args: ["--prometheus_port", "21400"]
        imagePullPolicy: Always
        ports:
        - name: tran-prome-port
          containerPort: 21400
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          requests:
            memory: "512Mi"
            cpu: 300m
          limits:
            memory: "1024Mi"
            cpu: 600m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: openim-config
            - configMap:
                name: openim-notification-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - msg-transfer
              topologyKey: kubernetes.io/hostname
  strategy:
    type: RollingUpdate 
