---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-deployment
spec:
  selector:
    matchLabels:
      app: friend
  replicas: 3 
  template:
    metadata:
      labels:
        app: friend 
    spec:
      containers:
      - name: friend
        image: openim/friend:v2.3.8
        imagePullPolicy: Always
        ports:
        - containerPort: 10120
          name: friend-port
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:10120"]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:10120"]
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          requests:
            memory: "256Mi"
            cpu: 150m
          limits:
            memory: "512Mi"
            cpu: 300m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: openim-config
            - configMap:
                name: openim-notification-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - friend
              topologyKey: kubernetes.io/hostname
  strategy:
    type: RollingUpdate 
---
apiVersion: v1
kind: Service
metadata:
  name: friend
spec:
  ports:
    - name: friend-svc-port
      protocol: TCP
      port: 10120
      targetPort: friend-port
  selector:
    app: friend
  type: ClusterIP  
