---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-deployment
spec:
  selector:
    matchLabels:
      app: msg
  replicas: 3 
  template:
    metadata:
      labels:
        app: msg 
    spec:
      containers:
      - name: msg
        image: openim/msg:errcode_alpha
        command: ["./main"]
        args: ["--port", "10130", "--prometheus_port","20130"]
        imagePullPolicy: Always
        ports:
        - containerPort: 10130
          name: msg-port
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:10130"]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:10130"]
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          requests:
            memory: "512Mi"
            cpu: 300m
          limits:
            memory: "1024Mi"
            cpu: 600m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: openim-config
            - configMap:
                name: openim-notification-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - group
              topologyKey: kubernetes.io/hostname
  strategy:
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  name: msg
spec:
  ports:
    - name: msg-svc-port
      protocol: TCP
      port: 10130
      targetPort: msg-port
  selector:
    app: msg
  type: ClusterIP  
